
# Edit SDC M&A names so it is consistent with GPF names

# Note that while M&A names are consistent with GPF, it might be not with NIC, which is my final goal

# Note that should apply all of these changes to both acquiror and target




MA_Unmatched.loc[MA_Unmatched[fieldname]=='1ST SOURCE BANKSOUTH BENDIN',fieldname] = '1ST SOURCE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='1ST SOURCE',fieldname] = '1ST SOURCE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ABN AMRO BANK NV COMMERCIAL',fieldname] = 'ABN AMRO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ABN AMRO BUSINESS UNIT',fieldname] = 'ABN AMRO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ABN AMRO HOLDING NV',fieldname] = 'ABN AMRO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ABN AMRO US PROFESSIONAL BRKG',fieldname] = 'ABN AMRO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ACCESS NATIONAL',fieldname] = 'ACCESS NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ADVEST GROUP INC(MONY GROUP)',fieldname] = 'ADVEST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ALEX BROWN',fieldname] = 'ALEX BROWN & SONS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ALLEGIANT BANKST LOUISMO',fieldname] = 'ALLEGIANT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ALLIANCE BANKDANVILLEIN',fieldname] = 'ALLIANCE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMEGY BANK INCTX',fieldname] = 'AMEGY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMERICAN NATIONAL BANKFREMONT',fieldname] = 'AMERICAN NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMERICAN NATIONAL BK OF TX',fieldname] = 'AMERICAN NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMERITRUST CORPCLEVELANDOH',fieldname] = 'AMERITRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMSOUTH BANKALABAMA',fieldname] = 'AMSOUTH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMSOUTH BANKBIRMINGHAM',fieldname] = 'AMSOUTH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='AMSOUTH BANKNASHVILLETN',fieldname] = 'AMSOUTH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ANB',fieldname] = 'ANB BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ANB',fieldname] = 'ANB BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ANDERSON BANK',fieldname] = 'ANDERSON BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ANDOVER BANK INCANDOVERMA',fieldname] = 'ANDOVER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ANDOVER BANK INCANDOVERMA',fieldname] = 'ANDOVER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ANDOVER BANKANDOVERMA',fieldname] = 'ANDOVER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ARVEST BANK GROUP INCAR',fieldname] = 'ARVEST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ASSOCIATED BANC',fieldname] = 'ASSOCIATED BANK GREEN BAY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ATLANTIC CAPITAL BANK',fieldname] = 'ATLANTIC CAPITAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANC ONE AKRON NAOHIO',fieldname] = 'BANK ONE AKRON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANCFIRST AUSTIN',fieldname] = 'BANCFIRST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK MUTUAL CORPWI',fieldname] = 'BANK MUTUAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF BOSTON CORPBOSTONMA',fieldname] = 'BANK OF BOSTON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF KENTUCKY FINL',fieldname] = 'BANK OF KENTUCKY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF KENTUCKY FINL',fieldname] = 'BANK OF KENTUCKY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF LEES SUMMITMISSOURI',fieldname] = 'BANK OF LEES SUMMIT'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF LIVERMORECALIFORNIA',fieldname] = 'BANK OF LIVERMORE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF LONG ISLANDBABYLON',fieldname] = 'BANK OF LONG ISLAND'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF NEW ENGLANDBOSTONMA',fieldname] = 'BANK OF NEW ENGLAND'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF SAN ANTONIO',fieldname] = 'THE BANK OF SAN ANTONIO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF SHOREWOODSHOREWOODIL',fieldname] = 'BANK OF SHOREWOOD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK OF VIRGINIA',fieldname] = 'BANK OF VIRGINIA TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK SOUTH CORPATLANTAGA',fieldname] = 'BANK SOUTH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANK SOUTH CORPATLANTAGA',fieldname] = 'BANK SOUTH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANKAMERICA',fieldname] = 'BANKAMERICA NATIONAL TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANKBOSTON CORPBOSTONMA',fieldname] = 'BANKBOSTON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANKERS TRUST NEW YORK',fieldname] = 'BANKERS TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BANKNORTH GROUP INCME',fieldname] = 'BANKNORTH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BARABOO NATIONAL BK FOND DU LAC',fieldname] = 'BARABOO NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BARABOO NATIONAL BK GREEN LAKE',fieldname] = 'BARABOO NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BARNETT BANK PALM BEACH',fieldname] = 'BARNETT BANK PALM BEACH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BATEMAN EICHLER HILL RICHARDS',fieldname] = 'BATEMAN EICHLER HILL RICHARDS REALTY SERVICES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BAYBANKS MIDDLESEX(BAYBANKS)',fieldname] = 'BAYBANK MIDDLESEX'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BAYBANKSBOSTONMASSACHUSETTS',fieldname] = 'BAYBANK BOSTON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BAYBANKSBOSTONMASSACHUSETTS',fieldname] = 'BAYBANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BB&T',fieldname] = 'BB&T FINANCIAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BB&T',fieldname] = 'BB&T FINANCIAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BC CHRISTOPHER SECURITIES',fieldname] = 'B C CHRISTOPHER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BEAR STEARNS COS',fieldname] = 'BEAR STEARNS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BEAR STEARNS MTG CAPITAL',fieldname] = 'BEAR STEARNS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BLUE RIDGE BANK NAFLOYDVA',fieldname] = 'BLUE RIDGE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BOATMENS BANKST LOUIS',fieldname] = 'BOATMENS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BOK FINANCIAL',fieldname] = 'BOK FINANCIAL SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BRENTON BANKSDES MOINESIA',fieldname] = 'BRENTON BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BROADWAY NATIONAL BANK BAYONNE NJ',fieldname] = 'BROADWAY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BROWN & CO SECURITIES',fieldname] = 'BROWN GIBBONS & CO SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BRYAN BANK OF GEORGIA',fieldname] = 'BRYANT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BSB BANK INCBINGHAMTONNY',fieldname] = 'BSB BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='BUCKHOLTS STATE BANKTEXAS',fieldname] = 'BUCKHOLTS STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CALDWELL STATE BANKKANSAS',fieldname] = 'CALDWELL STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CALIFORNIA FIRST BANKCA',fieldname] = 'CALIFORNIA FIRST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CANTON STATE BANKCANTONMN',fieldname] = 'CANTON STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CANTOR FITZGERALD IRELAND',fieldname] = 'CANTOR FITZGERALD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CASCO NORTHERN',fieldname] = 'CASCO NORTHERN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTENNIAL BANK INCAR',fieldname] = 'CENTENNIAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTERRE BANKST LOUIS',fieldname] = 'CENTERRE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTERSTATE BANK',fieldname] = 'CENTERSTATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTERSTATE BANKS',fieldname] = 'CENTERSTATE BANK OF FLORIDA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTRAL BANKMERIDENCT',fieldname] = 'CENTRAL BANK MERIDEN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTRAL PACIFIC',fieldname] = 'CENTRAL PACIFIC BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTURA BANK INCNC',fieldname] = 'CENTURY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTURY BANKGAINSVILLE(SUN)',fieldname] = 'CENTURY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CENTURY NATIONAL BANKHOUSTONTX',fieldname] = 'CENTURY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CHARTER BANK CORPFL',fieldname] = 'CARTER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CHASE MANHATTAN CORPNY',fieldname] = 'CHASE MANHATTAN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CHEMICAL BANK CORP NY',fieldname] = 'CHEMICAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CHIPPEWA VALLEY BANKWINTERWI',fieldname] = 'CHIPPEWA VALLEY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CIBC WORLD MARKETS US BUS',fieldname] = 'CIBC WORLD MARKETS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CITIZENS & NORTHERN',fieldname] = 'CITIZENS & NORTHERN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CITIZENS & SOUTHERN GA',fieldname] = 'CITIZENS & SOUTHERN NATIONAL BANKGA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CITIZENS NATIONAL BANK NAPLES',fieldname] = 'CITIZENS NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CITIZENS NATIONAL BANKATHENSTN',fieldname] = 'CITIZENS NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CITY NATIONAL BANKBEVERLY HILLS',fieldname] = 'CITY NATIONAL BANK BEVERLY HILLS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CIVISTA',fieldname] = 'CIVISTA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CNB BANKATTICAINDIANA',fieldname] = 'CNB BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CNB BANKGLOVERSVILLENY',fieldname] = 'CNB BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COLONIAL BANCGROUP INC BANKG',fieldname] = 'COLONIAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COLONIAL BANCGROUP',fieldname] = 'COLONIAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMERICA BANK TEXAS(COMERICA)',fieldname] = 'COMERICA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMERICA',fieldname] = 'COMERICA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMMERCIAL NATIONAL BANKCEDARTOWN',fieldname] = 'COMMERCIAL NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMMONWEALTH NATIONAL BANK OF DALLAS',fieldname] = 'COMMONWEALTH NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMMUNITY BANK OF NJNJ',fieldname] = 'NATIONAL COMMUNITY BANK OF NJ'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMMUNITY FIRST BANK INCKY',fieldname] = 'COMMUNITY FIRST BANK KY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMMUNITY STATE BANKIL',fieldname] = 'COMMUNITY STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMPASS BANK INCAL',fieldname] = 'COMPASS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='COMPASS BANK OF PLANOTEXAS',fieldname] = 'COMPASS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CONTINENTAL BANK INC PA',fieldname] = 'CONTINENTAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CONTINENTAL ILLINOIS',fieldname] = 'CONTINENTAL ILLINOIS NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CORNERSTONE BANK INCFL',fieldname] = 'CORNERSTONE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CORNERSTONE BANKNADALLASTX',fieldname] = 'CORNERSTONE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CREDIT LYONNAIS BELGIUM',fieldname] = 'CREDIT LYONNAIS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CRESTAR BANK(CRESTAR FINL)',fieldname] = 'CRESTAR BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CROCKER NATIONAL',fieldname] = 'CROCKER NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CROCKER NATIONAL(MIDLAND BANK)',fieldname] = 'CROCKER NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CROSSROADS BANKPERRYGA',fieldname] = 'CROSSROADS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='CUNNINGHAM SCHMERTZ',fieldname] = 'CUNNINGHAM SCHMERTZ & COINC'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DA DAVIDSON',fieldname] = 'DA DAVIDSON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DACOTAH BANKS INCABERDEENSD',fieldname] = 'DACOTAH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DEAN WITTER DISCOVER',fieldname] = 'DEAN WITTER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DELAWARE TRUST CODE',fieldname] = 'DELAWARE TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DENVER NATIONAL BANKDENVERPA',fieldname] = 'DENVER NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DEUTSCHE BANK AG US MUNICIPAL',fieldname] = 'DEUTSCHE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DEUTSCHE BANK AG',fieldname] = 'DEUTSCHE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DEUTSCHE BANK ALEX BROWN',fieldname] = 'ALEX BROWN & SONS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DEUTSCHE BANK SECURITIES DIV',fieldname] = 'DEUTSCHE BANK SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DIME SAVINGS BANK OF NY NJ OPS',fieldname] = 'DIME SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DISCOUNT CORP OF NEW YORK',fieldname] = 'DISCOUNT CORP OF NEW YORK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DRAPER BANKDRAPERUT',fieldname] = 'DRAPER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DREXEL BURNHAM LAMBERT INC MTG',fieldname] = 'DREXEL BURNHAM LAMBERT'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DREXEL BURNHAM LAMBERT SEATTLE',fieldname] = 'DREXEL BURNHAM LAMBERT'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DREYFUS BROKERAGE SERVICES',fieldname] = 'DREYFUS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DREYFUS',fieldname] = 'DREYFUS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='DUPAGE NATIONAL BANKWEST',fieldname] = 'DUPAGE NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='EAGLE BANKHELENAMONTANA',fieldname] = 'EAGLE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='EATON NATIONAL BNK&TRSTEATONOHIO',fieldname] = 'EASTON NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='EF HUTTON CREDIT',fieldname] = 'E F HUTTON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='EF HUTTON GROUP',fieldname] = 'E F HUTTON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='EQUIBANK(EQUIMARK CORP)',fieldname] = 'EQUIBANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ESSEX BANK INCNORFOLKVA',fieldname] = 'ESSEX BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ESSEX CAPITAL MARKETS',fieldname] = 'ESSEX'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='EXTEBANK DOMESTIC COML BANK BUS',fieldname] = 'EXTEBANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='F&M BANKROCHESTERIN',fieldname] = 'F&M BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='F&M MARQUETTE NBMINNEAPOLIS',fieldname] = 'MARQUETTE NATIONAL BANK MINNEAPOLIS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FAHNESTOCK VINER HOLDINGS',fieldname] = 'FAHNESTOCK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FARMERS EXCHANGE BANKKENTUCKY',fieldname] = 'FARMERS EXCHANGE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FARMERS NATIONAL BANK OF CANFIELD',fieldname] = 'FARMERS NATIONAL BANK OF CANFIELD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FARWELL STATE SAVINGS BANKMI',fieldname] = 'FARWELL STATE & SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIFTH THIRD BANK OF WESTERN OH',fieldname] = 'FIFTH THIRD BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIFTH THIRD SEC',fieldname] = 'FIFTH THIRD SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST & MERCHANTS',fieldname] = 'FIRST & MERCHANTS NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST & OCEAN NATIONAL BANKMA',fieldname] = 'FIRST & OCEAN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST CHARLOTTE FINANCIAL',fieldname] = 'FIRST CHARLOTTE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST CONTINENTAL FINANCIAL',fieldname] = 'FIRST CONTINENTAL FIN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST EASTERN CORPPA',fieldname] = 'FIRST EASTERN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST EASTERN CORPPA',fieldname] = 'FIRST EASTERN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST FIDELITY BANKNJ',fieldname] = 'FIRST FIDELITY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST FINANCIAL BANKOHIO',fieldname] = 'FIRST FINANCIAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST FINANCIAL',fieldname] = 'FIRST FINANCIAL SECURITES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST HAWAIIAN BANK',fieldname] = 'FIRST HAWAIIAN BANK HONOLULU'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST INDIANA BANK ELKHART',fieldname] = 'FIRST INDIANA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST INTERSTATE BANKCA',fieldname] = 'FIRST INTERSTATE BANK CALIFORNIA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST INTERSTATE BANKCA',fieldname] = 'FIRST INTERSTATE BANK CALIFORNIA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST JERSEY NATIONAL',fieldname] = 'FIRST JERSEY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST MACOMB BANK',fieldname] = 'FIRST MACOMB BANK MICHIGAN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST MARYLAND BANKMD',fieldname] = 'FIRST MARYLAND BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST MERCHANTS',fieldname] = 'FIRST MERCHANTS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST MID ILLINOIS BANK & TR',fieldname] = 'FIRST MID ILLINOIS BANK & TR'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST NATIONAL BANK OF DANVILLE',fieldname] = 'FIRST NATIONAL BANK OF DANVILLE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST NATIONAL BANK OF PLAINVIEW TX',fieldname] = 'FIRST NATIONAL BANK OF PLAINVIEW'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST NATIONAL BANK SO MARYLAND',fieldname] = 'FIRST NATIONAL BANK OF MARYLAND'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST NATIONAL BANKVALPARAISO',fieldname] = 'FIRST NATIONAL BANK VALPARAISOIN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST NATIONAL BNK OF OHIO AURORA',fieldname] = 'FIRST NATIONAL BANK OF OHIO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST NATIONALL BANK OF BARNESVILLE',fieldname] = 'FIRST NATIONAL BANK OF BARNESVILLE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST OF MICHIGAN CAPITAL',fieldname] = 'FIRST OF MICHIGAN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST SOUTHERN BANKNC',fieldname] = 'FIRST SOUTHERN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST SOUTHWESTERN TRUST',fieldname] = 'FIRST SOUTHEASTERN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST TENNESSEE BANK CORPTRUST',fieldname] = 'FIRST TENNESSEE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST UNITED BANK INCAL',fieldname] = 'FIRST UNITED BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRST WYOMING BANKWYOMING',fieldname] = 'FIRST WYOMING BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FIRSTIER',fieldname] = 'FIRSTIER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FISHKILL NATIONAL',fieldname] = 'FISHKILL NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FLAGSHIP BANKCLEVELANDOH',fieldname] = 'FLAGSHIP BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FLAGSHIP BANKS INCORLANDOFL',fieldname] = 'FLAGSHIP BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FLAGSHIP BANKWINSTED',fieldname] = 'FLAGSHIP BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FLEET NATIONAL BANKPROVIDENCE',fieldname] = 'FLEET NATIONAL BANK PROVIDENCE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FLORIDA COMMUNITY BANK',fieldname] = 'FLORIDA COMMUNITY BANKFL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FLORIDA COMMUNITY BANK',fieldname] = 'FLORIDA COMMUNITY BANKFL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FOUNDERS BANK',fieldname] = 'FOUNDERS BANK (IL)'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FRANKLIN BANCRP(UJB FINANCIAL)',fieldname] = 'FRANKLIN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FRANKLIN BANKWASHINGTONDC',fieldname] = 'FRANKLIN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='FULTON FINANCIAL',fieldname] = 'FULTON FINANCIAL ADVISORS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GENESIS CAPITAL',fieldname] = 'GENESIS CAPITAL MARKETS GROUP'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GEORGE K BAUM CERTAIN ASSETS',fieldname] = 'GEORGE K BAUM'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GEORGE K BAUM GROUP',fieldname] = 'GEORGE K BAUM'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GIRARD',fieldname] = 'GIRARD BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GLENVIEW STATE BANK LAND TRUST',fieldname] = 'GLENVIEW STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GOLDMAN SACHS GROUP',fieldname] = 'GOLDMAN SACHS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GOLDMAN SACHS INTL',fieldname] = 'GOLDMAN SACHS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GREAT LAKES BANK BUFFALO',fieldname] = 'GREAT LAKES BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GREAT SOUTHERN BANKFLORIDA',fieldname] = 'GREAT SOUTHERN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GREEN BELT BANK IOWA FALLS',fieldname] = 'GREEN BELT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='GUARANTY FIRST TRUST COMA',fieldname] = 'GUARANTY FIRST TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HANCOCK BANK INCKY',fieldname] = 'HANCOCK BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HANCOCK BANK INCKY',fieldname] = 'HANCOCK BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HARBOR NATIONAL BANK OF CT',fieldname] = 'HARBOR NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HARRIS BANKCORP INCCHICAGOIL',fieldname] = 'HARRIS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HC WAINWRIGHT',fieldname] = 'H C WAINWRIGHT'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HEARTLAND BANK INCIN',fieldname] = 'HEARTLAND BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HERITAGE BANK NJ',fieldname] = 'HERITAGE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HERITAGE BANK',fieldname] = 'HERITAGE BANK OF NORTH AMERICA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HERITAGE BANKING',fieldname] = 'HERITAGE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HIBERNIA NATIONAL BANK IN TEXAS',fieldname] = 'HIBERNIA NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HIBERNIA NATIONAL BANK IN TEXAS',fieldname] = 'HIBERNIA NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HILL COUNTRY BANKLEANDERTX',fieldname] = 'HILL COUNTRY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HILLSDALE COUNTY NATIONAL BANKMI',fieldname] = 'HILLSIDE COUNTY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HINSBROOK BANK INCIL',fieldname] = 'HINSBROOK BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HOME BANK INCFORT WAYNEIN',fieldname] = 'HOME BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HOME NATIONAL BANKMILFORDMA',fieldname] = 'HOME NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HOPPER SOLIDAY',fieldname] = 'HOPPER SOLIDAY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HORICON BANKWISCONSIN',fieldname] = 'HORICON BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HUDSON RIVER BANK INCNY',fieldname] = 'HUDSON RIVER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HUDSON UNITED BANKNJ',fieldname] = 'HUDSON UNITED BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HUNTINGTON BANK INCOH	',fieldname] = 'HUNTINGTON BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HUNTINGTON NATIONAL BANK',fieldname] = 'HUNTINGTON NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='HURON COMMUNITY BANKMI',fieldname] = 'HURON COMMUNITY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='IDAHO FIRST NATIONAL BANK BOISE',fieldname] = 'IDAHO FIRST NATIONAL BANK BOISE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='INDEPENDENT BANK GROUP',fieldname] = 'INDEPENDENT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='INTEGRA BANK NA BANKING',fieldname] = 'INTEGRA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='INVESTORS SAVINGS BANK FSB',fieldname] = 'INVESTORS SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JC BRADFORD',fieldname] = 'J C BRADFORD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JEFFERSON BANKFLORIDA',fieldname] = 'JEFFERSON BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JOHN NUVEEN CO INVEST BANK DIV',fieldname] = 'JOHN NUVEEN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JONES LANG LASALLE IP',fieldname] = 'JONES LANG LASALLE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JP MORGAN PARTNERS',fieldname] = 'JP MORGAN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JP MORGAN',fieldname] = 'JP MORGAN SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JPMORGAN CHASE',fieldname] = 'JP MORGAN CHASE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='JW CHARLES SECURITIES',fieldname] = 'J W CHARLES SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='KBW',fieldname] = 'KBW KEEFE BRUYETTE & WOODS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='KEMPER',fieldname] = 'KEMPER SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='KENSINGTON CA',fieldname] = 'KENSINGTON CAPITAL ADVISORS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='KILGORE FIRST NATIONAL BANKTX',fieldname] = 'KILGORE FIRST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='KIRKPATRICK PETTIS SMITH',fieldname] = 'KIRKPATRICK PETTIS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='KLEINBANKCHASKAMINNESOTA',fieldname] = 'KLEIN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LADENBURG THALMANN FINL SERVICES',fieldname] = 'LADENBURG THALMANN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LAFAYETTE BANKLAFAYETTEIN',fieldname] = 'LAFAYETTE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LAKE CITY BANKWARSAWINDIANA',fieldname] = 'LAKE CITY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LAKE FOREST BANKLIBERTYVIL',fieldname] = 'LAKE FOREST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LAKELAND COMMUNITY BANKIL',fieldname] = 'LAKELAND COMMUNITY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LAKELAND STATE BANKAUSTINTX',fieldname] = 'LAKELAND STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LANDMARK BANK CORP OF FL',fieldname] = 'LANDMARK BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LAPORTE BANK INCLAPORTEIN',fieldname] = 'LA PORTE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LASALLE BANK NA MUNICIPAL BOND',fieldname] = 'LASALLE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LCNB',fieldname] = 'LCNB NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LEGG MASON INVESTMENT COUNSEL',fieldname] = 'LEGG MASON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LEGG MASON',fieldname] = 'LEGG MASON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LEHMAN BROTHERS HOLDINGS',fieldname] = 'LEHMAN BROTHERS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LEHMAN BROTHERS HOLDINGS',fieldname] = 'LEHMAN BROTHERS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LF ROTHSCHILD & CO NY RETAIL',fieldname] = 'LF ROTHSCHILD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LF ROTHSCHILD HLDG INC TAMPA',fieldname] = 'LF ROTHSCHILD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LIBERTY SAVINGS BANKS FSB',fieldname] = 'LIBERTY SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LINCOLN BANK INCAR',fieldname] = 'LINCOLN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LINCOLN BANKIN',fieldname] = 'LINCOLN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LINCOLN SAVINGS BANKCARNEGIEPA',fieldname] = 'LINCOLN SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LISSTENNER & GOLDBERG',fieldname] = 'LISS TENNER & GOLDBERG'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='LLOYDS BANK',fieldname] = 'LLOYDS BANK CALIFORNIA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MAGNA BANK OF STHRN MISSOURI',fieldname] = 'MAGNA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MAHONING NATIONAL BANK',fieldname] = 'MAHONING NATIONAL BANK OF YOUNGSTOWN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MAIN STREET BANK INCPA',fieldname] = 'MAIN STREET BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MAIN STREET BANKS INCGA',fieldname] = 'MAIN STREET BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MAINE NATIONAL',fieldname] = 'MAINE NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MANUFACTURERS BANK OF FLORIDA',fieldname] = 'MANUFACTURERS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MANUFACTURERS HANOVER',fieldname] = 'MANUFACTURERS HANOVER SECCORP'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MANUFACTURERS HANOVER',fieldname] = 'MANUFACTURERS HANOVER SECCORP'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MARINE NATIONAL BANKIRVINECA',fieldname] = 'MAINE NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MARQUETTE BANK INCMN',fieldname] = 'MARQUETTE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MARQUETTE BANK',fieldname] = 'MARQUETTE NATIONAL BANK MINNEAPOLIS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MB FINANCIAL',fieldname] = 'MB FINANCIAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MCCLAIN COUNTY NATIONAL BANKOK',fieldname] = 'MCCLAIN COUNTY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MCDONALD & CO INVESTMENTS',fieldname] = 'MCDONALD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MELLON BANK CORPPITTSBURGHPA',fieldname] = 'MELLON BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MELLON NATIONAL',fieldname] = 'MELLON NATIONAL BANK & TR'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MERCANTILE NATIONAL BANKHAMMONDIN',fieldname] = 'MERCANTILE NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MERCHANTS NATIONAL',fieldname] = 'MERCHANTS NATIONAL BANK & TR'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MERRILL LYNCH HOLDINGS',fieldname] = 'MERRILL LYNCH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='METROPOLITAN BANCGROUP',fieldname] = 'METROPOLITAN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MICHIGAN NATIONAL',fieldname] = 'MICHIGAN NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MICHIGAN NATIONAL',fieldname] = 'MICHIGAN NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MID AMERICA NATIONAL BANK',fieldname] = 'MID AMERICAN NATIONAL BANK & TR'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MIDLAND BANK INCNJ',fieldname] = 'MIDLAND BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MIDLANTIC BANKS INCEDISONNJ',fieldname] = 'MIDLANTIC BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MIDLANTIC',fieldname] = 'MIDLANTIC BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MIDWEST BANKHAYSKS',fieldname] = 'MIDWEST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MIDWEST NATIONAL BANK INDIANAPOLIS',fieldname] = 'MIDWEST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MORGAN KEEGAN',fieldname] = 'MORGAN KEEGAN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MORGAN STANLEY GROUP',fieldname] = 'MORGAN STANLEY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MORGAN STANLEY GROUP',fieldname] = 'MORGAN STANLEY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MORGAN STANLEY SMITH BARNEY',fieldname] = 'SMITH BARNEY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='MORGAN STANLEY TRUST',fieldname] = 'MORGAN STANLEY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NATIONAL PENN BANKPA',fieldname] = 'NATIONAL PENN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NATIONAL PENN BANKPA',fieldname] = 'NATIONAL PENN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NATIONAL WESTMINSTER BANK',fieldname] = 'NATIONAL WESTMINSTER BANK USA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NBC CAPITAL',fieldname] = 'NBC CAPITAL MARKETS GROUP'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NCNB TEXAS NATIONAL BANKDALLAS',fieldname] = 'NCNB TEXAS NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NEW DARTMOUTH BANKNH',fieldname] = 'NEW DARTMOUTH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NEW DARTMOUTH BANKNH',fieldname] = 'NEW DARTMOUTH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NEW HAVEN SAVINGS BANKCT',fieldname] = 'NEW HAVEN SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NEWHARD COOK & CO RET OFFICES',fieldname] = 'NEWHARD COOK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NOMURA SECURITIES',fieldname] = 'NOMURA SECURITIES INTERNATIONA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NORSTAR BANKALBANYNY',fieldname] = 'NORSTAR BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NORTH FORK BANKMELVILLENY',fieldname] = 'NORTH FORK BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='NORTHPARK NATIONAL',fieldname] = 'NORTH PARK NATIONAL BANK OF TEXAS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OKLAHOMA STATE BANKGUTHRIEOK',fieldname] = 'OKLAHOMA STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OLD KENT BANK MECOSTA COUNTY',fieldname] = 'OLD KENT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OLD NATIONAL BANKEVANSVILLEIN',fieldname] = 'OLD NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OPPENHEIMER HOLDINGS',fieldname] = 'OPPENHEIMER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OPPENHEIMER MANAGEMENT',fieldname] = 'OPPENHEIMER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OPPENHEIMER(OPPENHEIMER GROUP)',fieldname] = 'OPPENHEIMER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='OPPENHEIMERFUNDS',fieldname] = 'OPPENHEIMER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ORANGE BANK',fieldname] = 'ORANGE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ORIX',fieldname] = 'ORIX BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PAINE WEBBER',fieldname] = 'BLYTH EASTMAN PAINE WEBBER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PARK STATE BANKNICOMA PARK',fieldname] = 'PARKE STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PARKWAY BANKILLINOIS',fieldname] = 'PARKWAY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PARTNERS TRUST FINANCIAL GROUP',fieldname] = 'PARTNERS TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PATRIOT BANK CORPPOTTSTOWNPA',fieldname] = 'PATRIOT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PEOPLES STATE BANKHAMTRAMCK',fieldname] = 'PEOPLES STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PHILADELPHIA NATIONAL',fieldname] = 'PHILADELPHIA NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PHOENIX NATIONAL BANK ARIZONA',fieldname] = 'NATIONAL BANK OF ARIZONA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PINNACLE BANK INCIL',fieldname] = 'PINNACLE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PIPER JAFFRAY COS',fieldname] = 'PIPER JAFFRAY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PIPER JAFFRAY COS',fieldname] = 'PIPER JAFFRAY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PITTSBURGH NATIONAL',fieldname] = 'PITTSBURGH NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PNC BANK CORPPITTSBURGHPA',fieldname] = 'PNC BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PNC FINANCIALPITTSBURGHPA',fieldname] = 'PNC FINANCIAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PORTER WHITE BANK OPERATION',fieldname] = 'PORTER WHITE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PREMIER BANKATLANTAGA',fieldname] = 'PREMIER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PREMIERBANK',fieldname] = 'PREMIER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PRESCOTT BALL & TURBEN(KEMPER)',fieldname] = 'PRESCOTT BALL & TURBEN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PRESCOTT BALL & TURBEN(KEMPER)',fieldname] = 'PRESCOTT BALL & TURBEN'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PRIME BANK OF CENTRAL FLORIDA',fieldname] = 'PRIME BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PROSPERITY BANK INCTX',fieldname] = 'PROSPERITY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PROVIDENT BANKOH',fieldname] = 'PROVIDENT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PRUDENTIAL BACHE SECURITIES',fieldname] = 'PRUDENTIAL BACHE SEC'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='PRUDENTIAL',fieldname] = 'PRUDENTIAL SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='QUINCY SAVINGS BANKQUINCYMA',fieldname] = 'QUINCY SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='QUINCY SAVINGS BANKQUINCYMA',fieldname] = 'QUINCY SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='RAGEN MACKENZIE GROUP',fieldname] = 'RAGEN MACKENZIE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='RAYMOND JAMES FINANCIAL',fieldname] = 'RAYMOND JAMES FINANCIAL INC'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='RBC CENTURA BANKS',fieldname] = 'RBC CENTURA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='REGIONS FINANCIAL CORPAL',fieldname] = 'REGIONS FINANCIAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='RENASANT',fieldname] = 'RENASANT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='REPUBLIC BANK INCFL',fieldname] = 'REPUBLIC BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ROBERTSON STEPHENS',fieldname] = 'BANCBOSTON ROBERTSON STEPHENS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ROBINSON HUMPHREY',fieldname] = 'THE ROBINSON HUMPHREY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ROCK RIVER BANKOREGONIL',fieldname] = 'ROCK RIVER BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ROLLING HILLS STATE BANKOK',fieldname] = 'ROLLING HILLS STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ROTAN MOSLE FINANCIAL',fieldname] = 'ROTAN MOSLE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='RYAN BECK HOLDINGS',fieldname] = 'RYAN BECK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SAFETY FUND',fieldname] = 'SAFETY FUND NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SALOMON BROTHERS HOLDING',fieldname] = 'SALOMON BROTHERS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SALOMON BROTHERS INC(SALOMON)',fieldname] = 'SALOMON BROTHERS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SANTA BARBARA BANKCA',fieldname] = 'SANTA BARBARA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SANWA BANK',fieldname] = 'THE SANWA BANK LIMITED'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SAVANNAH BANKSAVANNAHGA',fieldname] = 'SAVANNAH BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SCHEETZSMITH & CO PUBLIC',fieldname] = 'SCHEETZ SMITH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SCHRODERS',fieldname] = 'J HENRY SCHRODER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SCOTT & STRINGFELLOW FINANCIAL',fieldname] = 'SCOTT & STRINGFELLOW'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SEAFIRST',fieldname] = 'SEAFIRST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SEAGOVILLE STATE BANKTX',fieldname] = 'SEAGONVILLE STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SEATTLE NORTHWEST SECURITIES',fieldname] = 'SEATTLE NORTHWEST SEC'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SECURITY BANK OF KANSAS CITY',fieldname] = 'SECURITY BK OF KANSAS CITY KS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SECURITY BANK',fieldname] = 'SECURITY BANK CO MI'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SHAWMUT BANK NA(SHAWMUT NATIONAL)',fieldname] = 'SHAWMUT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SHEARSON LEHMAN BROTHERS HLDG',fieldname] = 'SHEARSON LEHMAN BROTHERS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SHEARSON LEHMAN HUTTON MTG',fieldname] = 'SHEARSON LEHMAN HUTTON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SHEARSON LEHMANAMERICAN',fieldname] = 'SHEARSON LEHMANAMERICAN EXPRE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SIEMENS',fieldname] = 'SIEMENS FINANCIAL SERVICES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SIGNATURE BANK CERT LOANSASTS',fieldname] = 'SIGNATURE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SIMMONS FIRST NATIONAL BANK BR',fieldname] = 'SIMMONS FIRST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SIMMONS FIRST NATIONAL',fieldname] = 'SIMMONS FIRST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SIMMONS FIRST NATIONAL',fieldname] = 'SIMMONS FIRST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SNB BANKMACONGA',fieldname] = 'SNB BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SOMERSET TRUST',fieldname] = 'SOMERSET TRUST CO PA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SOUTH STATE',fieldname] = 'SOUTH STATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SOUTHERN BANKGREENVILLESC',fieldname] = 'SOUTHERN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SOUTHWEST SECURITIES GROUP',fieldname] = 'SOUTHWEST SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SOVEREIGN BANK',fieldname] = 'SOVEREIGN BANK CAPITAL MARKETS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SPENCER SAVINGS BANK INC SLA',fieldname] = 'SPENCER SAVINGS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='STANDARD FEDERAL BANKTROYMI',fieldname] = 'STANDARD FEDERAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='STATE NATIONAL BANK OF MARLOWOK',fieldname] = 'STATE NATIONAL BANK OF MARLOW'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='STATE STREET',fieldname] = 'STATE STREET CAPITAL MARKETS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='STEPHENS HOLDING',fieldname] = 'STEPHENS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='STOCKMENS BANKKINGMANAZ',fieldname] = 'STOCKMANS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='STONEGATE BNKF LAUDERDALEFL',fieldname] = 'STONEGATE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUBURBAN BANKOHIO',fieldname] = 'SUBURBAN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUMITOMO BANK OF CALIFORNIA',fieldname] = 'SUMITOMO BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUMMIT BANKSAN ANTONIOTEXAS',fieldname] = 'SUMMIT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUN BANK INCSELINSGROVEPA',fieldname] = 'SUN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUN BANK INCVINELANDNJ',fieldname] = 'SUN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUNAMERICA(CHEMICAL BANK)',fieldname] = 'CHEMICAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUNTRUST BANKS',fieldname] = 'SUNTRUST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUNTRUST BANKS',fieldname] = 'SUNTRUST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='SUNTRUST BANKS',fieldname] = 'SUNTRUST BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TD BANK FINANCIAL GROUP',fieldname] = 'TD BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TD BANKNORTH INCPORTLANDME',fieldname] = 'TD BANKNORTH'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TD SECURITIES',fieldname] = 'TD SECURITIES (USA)'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TEHAMA COUNTY BANKRED BLUFF',fieldname] = 'TEHAMA COUNTY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TEXAS CAPITAL BANKDALLAS',fieldname] = 'TEXAS CAPITAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='THE BANK OF COMMERCE',fieldname] = 'BANK OF COMMERCE'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='THE CECILIAN BANK',fieldname] = 'CECILIAN BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='THOMSON MCKINNON RET BROKERAGE',fieldname] = 'THOMSON MCKINNON SEC'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='THOMSON MCKINNON SECURITIES',fieldname] = 'THOMSON MCKINNON SEC'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='THREE RIVERS BANK INCPA',fieldname] = 'THREE RIVERS BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TOKAI BANK',fieldname] = 'THE TOKAI BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TROY FINANCIAL CORPTROYNY',fieldname] = 'TROY FINANCIAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TRUST CO OF GEORGIAATLANTA',fieldname] = 'TRUST CO OF GEORGIA'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TRUST CO OF NEW JERSEYNJ',fieldname] = 'TRUST CO OF NEW JERSEY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='TUCKER ANTHONY & RL DAY',fieldname] = 'TUCKER ANTHONY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='UMB BANK NAKANSAS CITYMO',fieldname] = 'UMB BANK NA KANSAS CITY'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='UNION TRUST BANK',fieldname] = 'UNION TRUST'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='UNION TRUST COSTANFORDCT',fieldname] = 'UNION TRUST CO STAMFORD'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='UNITED COMMUNITY BANKS',fieldname] = 'UNITED COMMUNITY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='UNITED JERSEY BANKCENTRAL',fieldname] = 'UNITED JERSEY BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='UNITED MISSOURI BANK',fieldname] = 'UNITED MISSOURI BANK ST LOUIS'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='US BANK NAMINNEAPOLISMN',fieldname] = 'US BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='US BANK NAMINNEAPOLISMN',fieldname] = 'US BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='US BANKMINNEAPOLISMINNESOTA',fieldname] = 'US BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VALLEY BANKAPPLETONWI',fieldname] = 'VALLEY BANK APPLETON'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VALLEY BANKAPPLETONWI',fieldname] = 'VALLEY BANKAPPLETONWI'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VALLEY NATIONAL BANK GLENDALECA',fieldname] = 'VALLEY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VALLEY NATIONAL BANKNJ',fieldname] = 'VALLEY NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VECTRA BANK CORPDENVERCO',fieldname] = 'VECTRA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VIKING BANKSEATTLE',fieldname] = 'VIKING BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='VINING SPARKS IBG LP',fieldname] = 'VINING SPARKS IBG LTD PRTSHP'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WACHOVIA BANK NANC',fieldname] = 'WACHOVIA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WACHOVIA BANK OF N CAROLINANC',fieldname] = 'WACHOVIA BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WACHOVIA SECURITIES FINL HLDG',fieldname] = 'WACHOVIA SECURITIES'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WAYNE HUMMER INVESTMENTS',fieldname] = 'WAYNE HUMMER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WELLS FARGO ASSET MANAGEMENT',fieldname] = 'WELLS FARGO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WELLS FARGO CAPITAL C',fieldname] = 'WELLS FARGO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WELLS FARGO CAPITAL C',fieldname] = 'WELLS FARGO'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WESTERN ALLIANCE BANKNV',fieldname] = 'WESTERN ALLIANCE BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WESTLB AG SUBSCRIPTION FINANCE',fieldname] = 'WESTLB'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WESTPORT BANKWESTPORTCT',fieldname] = 'WESTPORT BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WINTRUST FINANCIAL CORPIL',fieldname] = 'WINTRUST FINANCIAL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WM E POLLOCK GOVT SECURITIES',fieldname] = 'WM E POLLOCK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WOODFOREST NATIONAL BANKHOUSTONTX',fieldname] = 'WOODFOREST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WOODFOREST NATIONAL BK BUSINESS',fieldname] = 'WOODFOREST NATIONAL BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='WY CAMPBELL',fieldname] = 'W Y CAMPBELL'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='XXXXXXX',fieldname] = 'XXXXXXX'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='YORK BANK',fieldname] = 'THE YORK BANK'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ZIEGLER LOTSOFF CAPITAL MGMT L',fieldname] = 'ZIEGLER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ZIEGLER WEALTH MGMT',fieldname] = 'ZIEGLER'
MA_Unmatched.loc[MA_Unmatched[fieldname]=='ZIONS FIRST NATIONAL BANKSALT LAKE',fieldname] = 'ZIONS FIRST NATIONAL BANK'

